### ISSUE TITLE
Pulling and sending beacon errors

### ISSUE THREAD

**Issue by DoZ10** [bluscreenofjeff/AggressorScripts#2]
Pulling or sending beacons from/to Empire fails with the following error:

C:\Users\someuser>curl --insecure -i -H Content-Type:application/json https://8.8.8.8:1337/api/stagers?token=s55jia8hfdghfdghfdghfdhdfhailx942m -X POST -d {"StagerName":"launcher","Listener":"test","Base64":"True"}

HTTP/1.0 400 BAD REQUEST
Content-Type: text/html
Content-Length: 192
Server: Werkzeug/0.10.4
Date: Wed, 30 Nov 2016 19:06:50 GMT

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The browser (or proxy) sent a request that this server could not understand.</p>

I am using CURL for Windows 7.51.0 

Thanks

**Comment by bluscreenofjeff** [comment]
Hi DoZ10,

Are you having this issue with Beaconpire or trying to curl directly in the command line?

**Comment by DoZ10** [comment]
Hi,

I actually found the initial problem. Double quotes are striped in the body of POST Requests on Windows.
But even with that fixed (dirty fix) I run into several other problems ... don't know yet if related. But now JSON request seem ok but REST server answers "bad agent name" which is supposed to be good.. (CRLF problems ???)

Guess I shouldn't be operating this on Windows :P

**Comment by bluscreenofjeff** [comment]
The requests will originate from the Cobalt Strike teamserver, which requires Linux. It sounds like you may be having Empire RESTful API usage issues, rather than issues with Beaconpire. I'd dig through the documentation and do some further testing.

Closing this issue since it's unrelated to the Beaconpire script.
