### ISSUE TITLE
it is compatible with Empire 2.0.0

### ISSUE THREAD

**Issue by PentestinGxRoot** [bluscreenofjeff/AggressorScripts#3]
_______ .___  ___. .______    __  .______       _______
  |   ____||   \/   | |   _  \  |  | |   _  \     |   ____|
  |  |__   |  \  /  | |  |_)  | |  | |  |_)  |    |  |__
  |   __|  |  |\/|  | |   ___/  |  | |      /     |   __|
  |  |____ |  |  |  | |  |      |  | |  |\  \----.|  |____
  |_______||__|  |__| | _|      |__| | _| `._____||_______|

       264 modules currently loaded

X >  Hi Boss, I have problems when creating the listener.
X > I would like to know if it is compatible with Empire 2.0.0?

X > Thank you

**Comment by bluscreenofjeff** [comment]
Assuming the question is about Beaconpire, no the script is not compatible with Empire 2.0. I hope to add 2.0 support when the 2.0 API is officially released.

Thanks!
